### ISSUE TITLE
Get Jekyll-Store running

### ISSUE THREAD

**Issue by agush22** [jekyll-store/front#1]
Hi!
I was wondering if there's some kind of guide to get the jekyll store running.
At least how to connect the engine with the front would be appreciated.

Seems like a very interesting project but right now I'm stuck with the different pieces and don't really know how to put them together.

**Comment by mushishi78** [comment]
I will be getting round to writing a getting started documentation, it's just a matter finding some free time.

The engine is already compiled in the front. It's listed as a dependency in the [`package.json`](https://github.com/jekyll-store/front/blob/gh-pages/package.json) file and is required in the [`assets/_js/index.js`](https://github.com/jekyll-store/front/blob/gh-pages/assets/_js/index.js) file, so it was included in the [`assets/_js/compiled.js`](https://github.com/jekyll-store/front/blob/gh-pages/assets/_js/compiled.js) when I ran browserify before committing.

The easiest steps to deploy are roughly:

* Fork the [front](https://github.com/jekyll-store/front/fork) and the [microservice](https://github.com/jekyll-store/microservice/fork)
* Deploy the microservice to a hosting platform, like Heroku.
* Edit the [_config.yml](https://github.com/jekyll-store/front/blob/gh-pages/_config.yml) in the front
* Supply the microservice with [environment variables](https://github.com/jekyll-store/microservice#environment-variables)
* Setup a [reset hook](https://github.com/jekyll-store/front#reset-hook)

I hope that can get you started, but there's really quite a lot that needs documenting, so feel free to ask more questions.

**Comment by agush22** [comment]
These were exactly the pointers that I needed. 
For some reason I had to delete ```baseurl: /front``` from config.yml for jekyll to serve it correctly in my local machine but other than that I got it running.

as for modifying the store I think it will take more time for me, as I'm not well versed in Flux... 

Anyway his project is really cool, thanks! 
Feel free to close the issue.

**Comment by mushishi78** [comment]
Cool. You should read this [documentation about `baseurl`] (http://jekyllrb.com/docs/github-pages/#project-page-url-structure). I've provided the shorthand `npm run serve` for running jekyll without baseurl as well.
