### ISSUE TITLE
Is http://www.jekyll-store.com hijacked?

### ISSUE THREAD

**Issue by brandonjbjelland** [jekyll-store/front#4]
I'm redirected to any of a couple different ad sites. Could be that my computer has some sort of malware but I've checked from a mobile phone as well and see the same result. Is every last device I have does some odd redirection. When trying through my VPN connection, I get a slightly different behavior and I'm only redirected as far as http://ww12.jekyll-store.com/ or http://ww8.jekyll-store.com/.

Can anyone else confirm?

**Comment by mushishi78** [comment]
I let the domain go and failed to remove the link from the description here. Sorry for causing confusion.
